import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import AppHeader from "@/components/AppHeader/AppHeader";
import AppFooter from "@/components/AppFooter";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NexCart",
  description: "Generated by arikxl",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className='min-h-screen flex flex-col'>
            <AppHeader />
            {children}
            <AppFooter />
          </div>
        </Providers>
      </body>
    </html>
  );
}
